export const CLOUD_PRESETS = [
  { value: 'Preset1',       label: 'Light Scattered 1' },
  { value: 'Preset2',       label: 'Light Scattered 2' },
  { value: 'Preset3',       label: 'High Scattered 1' },
  { value: 'Preset4',       label: 'High Scattered 2' },
  { value: 'Preset5',       label: 'Scattered 1' },
  { value: 'Preset6',       label: 'Scattered 2' },
  { value: 'Preset7',       label: 'Scattered 3' },
  { value: 'Preset8',       label: 'High Scattered 3' },
  { value: 'Preset9',       label: 'Scattered 4' },
  { value: 'Preset10',      label: 'Scattered 5' },
  { value: 'Preset11',      label: 'Scattered 6' },
  { value: 'Preset12',      label: 'Scattered 7' },
  { value: 'Preset13',      label: 'Broken 1' },
  { value: 'Preset14',      label: 'Broken 2' },
  { value: 'Preset15',      label: 'Broken 3' },
  { value: 'Preset16',      label: 'Broken 4' },
  { value: 'Preset17',      label: 'Broken 5' },
  { value: 'Preset18',      label: 'Broken 6' },
  { value: 'Preset19',      label: 'Broken 7' },
  { value: 'Preset20',      label: 'Broken 8' },
  { value: 'Preset21',      label: 'Overcast 1' },
  { value: 'Preset22',      label: 'Overcast 2' },
  { value: 'Preset23',      label: 'Overcast 3' },
  { value: 'Preset24',      label: 'Overcast 4' },
  { value: 'Preset25',      label: 'Overcast 5' },
  { value: 'Preset26',      label: 'Overcast 6' },
  { value: 'Preset27',      label: 'Overcast 7' },
  { value: 'RainyPreset1',  label: 'Overcast & Rain 1' },
  { value: 'RainyPreset2',  label: 'Overcast & Rain 2' },
  { value: 'RainyPreset3',  label: 'Overcast & Rain 3' },
  { value: 'RainyPreset4',  label: 'Light Rain 1' },
  { value: 'RainyPreset5',  label: 'Light Rain 2' },
  { value: 'RainyPreset6',  label: 'Light Rain 3' },
  { value: 'NEWRAINPRESET4', label: 'Light Rain 4' },
]
